//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1DatabaseApproach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int oid { get; set; }
        public string odate { get; set; }
        public string oname { get; set; }
        public string oqty { get; set; }
        public string price { get; set; }
        public string ostatus { get; set; }
        public Nullable<int> custId { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
